# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  wavetoy-progression-benchmarks:
    dependencies:
    - base
    - wavetoy-progression
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: Designing a WaveToy in Haskell, in progressively more elegant steps
executables:
  wavetoy-progression:
    dependencies:
    - base
    - monad-loops
    - wavetoy-progression
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable
extra-source-files:
- CHANGELOG.rst
- LICENSE.rst
- package.yaml
- README.rst
- stack.yaml
ghc-options: -Wall
github: eschnett/wavetoy-progression
library:
  dependencies:
  - base
  - vector
  source-dirs: library
license: MIT
maintainer: Erik Schnetter
name: wavetoy-progression
synopsis: A new Haskeleton package.
tests:
  wavetoy-progression-test-suite:
    dependencies:
    - base
    - tasty
    - tasty-hspec
    - tasty-quickcheck
    - tasty-smallcheck
    - wavetoy-progression
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '1.0.0'
